apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cart
  name: cart
spec:
  ports:
  - name: cart
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: cart
  type: LoadBalancer
status:
  loadBalancer: {}
